export const ar = {
  LIVE: {
    JOIN_SESSIONS: 'الانضمام إلى الجلسات',
    GROUP_SESSION: 'جلسة جماعية',
    SOLO_SESSION: 'جلسة فردية',
    SESSION_TITLE: 'عنوان الجلسة',
    SESSION_DESCRIPTION: 'وصف الجلسة',
    SESSION_Instructor : 'معلم الجلسة' ,
    NUMBER_OF_SEATS: 'عدد المقاعد',
    SESSION_PRICE: 'سعر الجلسة',
    DATE_TIME: 'التاريخ والوقت',
    SELECT_DATE: 'اختر التاريخ',
    SELECT_TIME: 'اختر الوقت',
    CREATE_SESSION: 'إنشاء جلسة',
    AVAILABLE_SESSIONS: 'الجلسات {{type}} المتاحة',
    NO_SESSIONS: 'لا توجد جلسات {{type}}.',
    DELETE: 'حذف',
    DELETE_CONFIRM: 'هل أنت متأكد أنك تريد حذف هذه الجلسة؟',
    CREATE_SUCCESS: 'تم إنشاء الجلسة بنجاح',
    FETCH_ERROR: 'حدث خطأ أثناء جلب الجلسات',
    CREATE_FAIL: 'فشل في إنشاء الجلسة',
    DELETE_SUCCESS: 'تم حذف الجلسة بنجاح',
    DELETE_FAIL: 'فشل في حذف الجلسة',
    DATE : "تاريخ",
    TIME : "وقت" ,
    ACTIONS : "حدث",
     UPCOMING_GROUP: 'الجلسات الجماعية القادمة',
    UPCOMING_SOLO: 'الجلسات الفردية القادمة',
    STUDENT_NAME: 'اسم الطالب',
    STUDENT_IMAGE: 'صورة ',
    STUDENT_BOOK: 'عدد_الطلاب_الحاجزين',
    TITLE: 'العنوان',
    ACTION: 'الإجراء',
    JOIN: 'انضمام',
    CANCEL: 'إلغاء',
    NOW_IN_SESSION: 'أنت الآن في الجلسة',
    JOIN_SUCCESS: 'تم الانضمام للجلسة بنجاح!',
    JOIN_FAILED: 'فشل في الانضمام للجلسة',
    CANCEL_SUCCESS: 'تم إلغاء الجلسة بنجاح!',
    CANCEL_FAILED: 'فشل في إلغاء الجلسة',
    JOIN_ROOM: 'انضم للغرفة'
  }
};
