export const en = {
  LIVE: {
    JOIN_SESSIONS: 'Join Sessions',
    GROUP_SESSION: 'Group Session',
    SOLO_SESSION: 'Solo Session',
    SESSION_TITLE: 'Session Title',
    SESSION_DESCRIPTION: 'Session Description',
    SESSION_Instructor : 'Session Instructor' ,
    NUMBER_OF_SEATS: 'Number of Seats',
    SESSION_PRICE: 'Session Price',
    DATE_TIME: 'Date & Time',
    SELECT_DATE: 'Select Date',
    SELECT_TIME: 'Select Time',
    CREATE_SESSION: 'Create Session',
    AVAILABLE_SESSIONS: 'Available {{type}} Sessions',
    NO_SESSIONS: 'No {{type}} sessions found.',
    DELETE: 'Delete',
    DELETE_CONFIRM: 'Are you sure you want to delete this session?',
    CREATE_SUCCESS: 'Session created successfully',
    FETCH_ERROR: 'Error fetching sessions',
    CREATE_FAIL: 'Failed to create session',
    DELETE_SUCCESS: 'Session deleted successfully',
    DELETE_FAIL: 'Failed to delete session',
    DATE : "Date",
    TIME : "Time" ,
    ACTIONS : "ACTIONS",
    JOIN_SUCCESS: 'Session joined successfully!',
    JOIN_FAILED: 'Failed to join session',
    CANCEL_SUCCESS: 'Session cancelled successfully!',
    CANCEL_FAILED: 'Failed to cancel session',
    JOIN_ROOM: 'Join Room',
     UPCOMING_GROUP: 'Upcoming Group Sessions',
    UPCOMING_SOLO: 'Upcoming Solo Sessions',
    STUDENT_NAME: 'Student Name',
    STUDENT_IMAGE: 'Student Image',
    STUDENT_BOOK : 'BookedStudentsCount',
    TITLE: 'Title',
    ACTION: 'Action',
    JOIN: 'Join',
    CANCEL: 'Cancel',
    NOW_IN_SESSION: 'Now in session',

  }
};
