// ar.ts
export const ar = {
  PROFILE: {
    EMAIL: "البريد الإلكتروني",
    PHONE: "رقم الهاتف",
    EXPERIENCE: "الخبرة",
    JOIN_DATE: "تاريخ الانضمام",
    WALLET_BALANCE: "رصيد المحفظة",
    COUNTRY: "الجنسية",
    COUNTRY_EGYPTIAN: "مصري",
    COUNTRY_SAUDI: "سعودي",
    COUNTRY_UNKNOWN: "غير معروف",
    UPDATE: "تعديل",
    UPDATE_PASSWORD: "تعديل كلمة المرور",
    ADD_BANK_ACCOUNT: "إضافة حساب بنكي",
    BANK_ACCOUNT_NUMBER: "رقم الحساب البنكي",
    BANK_ACCOUNT_NAME: "اسم صاحب الحساب",
    BANK_NAME: "اسم البنك",
    BANK_CODE: "كود البنك",
    SAVE_ACCOUNT: "حفظ الحساب",
    TOAST_SUCCESS: "تم إضافة الحساب البنكي بنجاح",
    TOAST_ERROR: "حدث خطأ أثناء إضافة الحساب البنكي",
    accountNumber: 'رقم الحساب',
  accountHolderName: 'اسم صاحب الحساب',
  bankName: 'اسم البنك',
  bankCode: 'كود البنك',
  createdAt: 'تاريخ الإنشاء',
  updatedAt: 'تاريخ التحديث',
  actions: 'الإجراءات',
  delete: 'حذف',
  EDIT_PROFILE : "تعديل الملف الشخصي",
  FIRST_NAME : 'الاسم الاول' ,
  LAST_NAME : 'الاسم الاخير',
  SAVE : 'حفظ',
OLD_PASSWORD: 'كلمة المرور القديمة',
  NEW_PASSWORD: 'كلمة المرور الجديدة',
  UPDATEE_PASSWORD: 'تحديث كلمة المرور',
  PASSWORD_UPDATE_SUCCESS: 'تم تحديث كلمة المرور بنجاح!',
  PASSWORD_UPDATE_ERROR: 'حدث خطأ ما.'
  }
};
